x = input("podaj x:")
y = input("podaj y:")
print('x =', x)
print('y =', y)
print('Wynik dodawania:',int(x) + int(y))
print('Wynik odejmowania:', int(x) - int(y))
print('Wynik mnożenia:', int(x) * int(y))
print('wynik dzielenia:', int(x) / int(y))
print('wynik dzielenia całkowitego:', int(x) // int(y))
print('wynik reszty z dzielenia:', int(x) % int(y))
print('wynik potęęgowania:', int(x) ** int(y))